config/routes.rb
Bancodeideias::Application.routes.draw do
  get "votos/create"
  get "votos/update"
  resources :projetos do
    resources :comentarios
    resources :votos, only: [:create, :update]
  end

  devise_for :users
  get "home/index"

  root 'home#index'

  

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :projeto  
end

app/models/projeto.rb
class Projeto < ActiveRecord::Base
	belongs_to :user
	has_many :comentarios, dependent: :destroy
	has_many :votos, dependent: :destroy

	scope :mais_recentes, -> { order('created_at DESC') }

  def self.mais_votados
  	Projeto.all.sort! {|a,b| a.votos.sum(:pontos) <=> b.votos.sum(:pontos) }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

	validates :username, presence: true
	has_many :projetos, dependent: :destroy
end

app/models/voto.rb
class Voto < ActiveRecord::Base
	POINTS = (1..5).to_a
  belongs_to :projeto
  belongs_to :user

  validates_inclusion_of :pontos, in: POINTS
  validates_presence_of :pontos, :user_id, :projeto_id
  validates_uniqueness_of :user_id, scope: :projeto_id

  def self.stars
  	(average(:pontos) || 0).round
  end	  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) do |u|
        u.permit :username, :email, :password, :password_confirmation
      end
    end  
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
	before_action :authenticate_user!, only: [:create, :destroy]

	def create
		@comentario = projeto.comentarios.build(comentarios_params)

    if @comentario.save
      redirect_to projeto, notice: 'Comentário adicionado com sucesso.' 
    else
      redirect_to projeto, :flash => { :error => "Erro ao adicionar comentário, bitch" }
    end
	end

	def destroy
		@comentario = Comentario.find(params[:id])
		@comentario.destroy
		redirect_to @comentario.projeto
	end

	private

	def projeto
		@projeto ||= current_user.projetos.find(params[:projeto_id])
	end

	def comentarios_params
		params.require(:comentario).permit(:pontos, :comentario)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@projetos_mais_votados = Projeto.mais_votados
  	@projetos_mais_recentes = Projeto.mais_recentes
  end
end

app/controllers/projetos_controller.rb
class ProjetosController < ApplicationController
  before_action :set_projeto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  # GET /projetos
  # GET /projetos.json
  def index
    @projetos = current_user.projetos
  end

  # GET /projetos/1
  # GET /projetos/1.json
  def show
    if user_signed_in?
      @user_voto = @projeto.votos.find_or_initialize_by(user_id: current_user.id)
    end
  end

  # GET /projetos/new
  def new
    @projeto = current_user.projetos.build
  end

  # GET /projetos/1/edit
  def edit
  end

  # POST /projetos
  # POST /projetos.json
  def create
    @projeto = current_user.projetos.build(projeto_params)

    respond_to do |format|
      if @projeto.save
        format.html { redirect_to @projeto, notice: 'Projeto was successfully created.' }
        format.json { render action: 'show', status: :created, location: @projeto }
      else
        format.html { render action: 'new' }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projetos/1
  # PATCH/PUT /projetos/1.json
  def update
    respond_to do |format|
      if @projeto.update(projeto_params)
        format.html { redirect_to @projeto, notice: 'Projeto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projetos/1
  # DELETE /projetos/1.json
  def destroy
    @projeto.destroy
    respond_to do |format|
      format.html { redirect_to projetos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projeto
      @projeto = Projeto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projeto_params
      params.require(:projeto).permit(:titulo, :descricao)
    end
end

app/controllers/votos_controller.rb
class VotosController < ApplicationController
	before_action :authenticate_user!

  def create
  	voto = projeto.votos.find_or_initialize_by(user_id: current_user.id)
  	voto.update!(voto_params)
  	head :ok
  end

  def update
  	create
  end

  def projeto
  	@projeto ||= Projeto.find(params[:projeto_id])
  end

  def voto_params
  	params.require(:voto).permit(:pontos)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projetos_helper.rb
module ProjetosHelper
end

app/helpers/votos_helper.rb
module VotosHelper
end

app/views/home/index.html.erb
<div class="page-header">
	<h1>Bem vindo ao Banco de Ideias</h1>

	<div class="row">
		<div class="col-md-4">
				<h2>Mais votados</h2>
				<% @projetos_mais_votados.each do |projeto| %>
					<div class="projetos">
						<p><strong><%= link_to projeto.titulo, projeto %></strong></p>
						<p><%= truncate projeto.descricao %></p>
						<p><%= projeto.user.username %> - <%= l(projeto.created_at, format: :short) %></p>
					</div>
				<% end %>
		</div>

		<div class="col-md-4">
			<h2>Mais recentes</h2>
			<% @projetos_mais_recentes.each do |projeto| %>
				<div class="projetos">
					<p><strong><%= link_to projeto.titulo, projeto %></strong></p>
			  	<p><%= truncate projeto.descricao %></p>				
					<p><%= projeto.user.username %> - <%= l(projeto.created_at, format: :short) %></p>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/layouts/_user_navbar.html.erb
<nav>
	<ul class="nav navbar-nav">
		<li><%= link_to 'Meus Projetos', projetos_path %></li>
		<li><%= link_to 'Perfil', edit_user_registration_path %></li>
		<li><%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
	</ul>
</nav>

app/views/layouts/_visitor_navbar.html.erb
<nav>
	<ul class="nav navbar-nav">
		<li><%= link_to 'Novo Usuário' , new_user_registration_path %></li>
		<li><%= link_to 'Login', new_user_session_path %></li>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Banco de Ideias</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

		<div id="wrap">

			<div class="navbar navbar-inverse navbar-fixed-top">
	      <div class="container">
	        <div class="navbar-header">
	          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button>
	          
	          <%= link_to 'Banco de Ideias', root_path, :class => 'navbar-brand' %>
	        </div>
	        <div class="collapse navbar-collapse">
							<% if user_signed_in? %>
								<%= render 'layouts/user_navbar' %>
							<% else %>
								<%= render 'layouts/visitor_navbar' %>
							<% end %>
	        </div>
	      </div>
	    </div>

			<div class="container">
				<% if notice.present? %>
					<div id="notice"> <%= notice %> </div>
				<% end %>
				
				<% if alert.present? %>
					<div id="alert"><%= alert %></div>
				<% end %>

				<%= yield %>		
			</div>
		</div>

		<footer id="footer">
			<div class="container">
				<p>by <a href="http://twitter.com/rodrigorosa">@rodrigorosa</a></p>
			</div>
		</footer>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </body>
</html>

app/views/projetos/_form.html.erb
<%= form_for(@projeto) do |f| %>
  <% if @projeto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@projeto.errors.count, "error") %> prohibited this projeto from being saved:</h2>

      <ul>
      <% @projeto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo, :autofocus => true %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_area :descricao, :cols => 70, :rows => 15 %>
  </div>
  <div class="actions">
    <%= f.submit 'Criar Projeto' %>
  </div>
<% end %>

app/views/projetos/_voto.html.erb
<section class="voto">
	<% if user_signed_in? %>
		<%= form_for [voto.projeto, voto], remote: true do |f|  %>
			<% Voto::POINTS.each do |point| %>
				<%= f.radio_button :pontos, point %>
				<%= f.label :pontos, point, value: point %>
			<% end %>
			<%= f.submit %>
		<% end %>
	<% else %>
		<span class="login_required">
			Login requerido
		</span>
	<% end %>
</section>

app/views/projetos/edit.html.erb
<h1>Editando projeto</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @projeto %> |
<%= link_to 'Voltar', projetos_path %>

app/views/projetos/index.html.erb
<h1>Meus projetos</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descricao</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projetos.each do |projeto| %>
      <tr>
        <td><%= link_to projeto.titulo, projeto %></td>
        <td><%= projeto.descricao %></td>
        <td>
          <%= link_to 'Editar', edit_projeto_path(projeto), :class => 'btn btn-xs btn-primary' %>
          <%= link_to 'Excluir', projeto, method: :delete, data: { confirm: 'Tem certeza?' }, :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Projeto', new_projeto_path, :class => 'btn btn-primary' %>

app/views/projetos/new.html.erb
<h1>Novo projeto</h1>

<%= render 'form' %>

<%= link_to 'Voltar', projetos_path %>

app/views/projetos/show.html.erb
<p id="notice">
	<%= notice %>
</p>

<h1><%= @projeto.titulo %></h1>
<p><%= @projeto.descricao %></p>

<h2>Comentários</h2>
<% @projeto.comentarios.each do |comentario| %>
  <p><%= comentario.comentario %></p>
  
  <p><%= link_to "Excluir comentário", [@projeto, comentario], :method => :delete, :confirm => "Are you sure?" %></p>
<% end %>

<%= render partial: 'voto', object: @user_voto %>

<%= form_for [@projeto, @projeto.comentarios.build] do |f| %>
  <p><%= f.text_area :comentario, :size => '40x10' %></p>
  <p><%= f.submit "Adicionar comentário" %></p>
<% end %>

<%= link_to 'Voltar', projetos_path %>